@startuml
left to right direction
skinparam packageStyle rectangle
actor Профессор
actor Студент
actor Персонал

rectangle "Система обучения" {
    Профессор --> (Принимает экзамен)
    Профессор --> (Управляет курсом)
    Профессор ---> (Доступ к информации о курсе)
    Студент ---> (Доступ к информации о курсе)   
    Студент ---> (Записался на курсы)
    Персонал ---> (Доступ к информации о курсе)
    Персонал ---> (Управляет курсом)  
}
@enduml