@startuml

actor "Front" as front

participant "Сервис справок" as report
database "База данных" as db

front -> report: Получение список справок
activate report
report -> db:  Получение список справок из бд
activate db
db --> report:  Список справок
deactivate db
report -> front: Список справок
deactivate report

@enduml